name: Sync

on:
  push:
    branches: master
    
  schedule:
    - cron: '0 * * * *'
      
jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        token: ${{ secrets.PAT }}
    - name: Setup
      run: |           
        git config --global user.name ${GITHUB_ACTOR}
        git config --global user.email ${GITHUB_ACTOR}@wy-lang.org
        git remote add upstream https://github.com/wenyan-lang/wenyan.wiki.git
    - name: Fetch
      run: git fetch upstream
    - name: Checkout
      run: git checkout origin/master
    - name: Merge
      run: git merge upstream/master
    - name: Branch
      run: git branch master
    - name: Push
      run: |
        git push "https://${GITHUB_ACTOR}:${{secrets.PAT}}@github.com/wenyan-lang/wiki.git" HEAD:master
        git push "https://${GITHUB_ACTOR}:${{secrets.PAT}}@github.com/wenyan-lang/wenyan.wiki.git" HEAD:master
     
