name: Sync

on:
  push:
    branches: master
    
  schedule:
    - cron: '0 * * * *'
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        token: ${{ secrets.PAT }}
    - name: Setup
      run: |           
        git config --global user.name ${GITHUB_ACTOR}
        git config --global user.email ${GITHUB_ACTOR}@wy-lang.org
        git remote add upstream https://github.com/wenyan-lang/wenyan.wiki.git
    - name: Fetch
      run: git fetch upstream
    - name: Checkout
      run: git checkout origin/master
    - name: Merge
      run: git merge upstream/master
    - name: Branch
      run: git branch master
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PAT }}
